USE [Mystore]
GO

/****** Object:  Index [PK__Customer__8CB286B9F7D89168]    Script Date: 3/16/2018 3:24:26 AM ******/
ALTER TABLE [dbo].[Customers] ADD  CONSTRAINT [PK__Customer__8CB286B9F7D89168] PRIMARY KEY CLUSTERED 
(
	[Customer_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
